### ISSUE TITLE
Error: cannot connect to display 

### ISSUE THREAD

**Issue by Bhanu2-P** [PrincetonUniversity/Coursera-SDN#62]
Through error message when
Type command > xterm __
 Error: cannot connect to display 
In case dhclient ...
xterm: No absolute path found for shell : eth1
How to fix this??

**Comment by nrasadi** [comment]
There are a few steps that you should probably do beforehand.

1. Make sure you have installed X11 server on the host machine. For example, if you are using Windows, Xming is usually the first option.
2. check whether your $DISPLAY is empty or not.
```bash
echo $DISPLAY
```
3. If empty, use `route` within your running VM to find the gateway. You may also see the gateway (host) IP once you log in. 
4. Add gateway to your DISPLAY. Open the `.bashrc` file, and add the following to the end of it:
```bash
export DISPLAY=[your gateway's ip address]:0.0   # E.g.: 10.0.2.2:0.0
```
5. Use `source .bashrc` afterwards, to apply the update.
6. Check if the xterm works or not.

Does the problem still exists?
- [ ] Run vagrant via `vagrant ssh -- -vvv`, to see logs.
- [ ] If on Windows, use another X server, e.g., [VcXsrv](https://sourceforge.net/projects/vcxsrv/).

Also, since this repo has not been updated for a long time, I would suggest using a more updated one. For instance, UofW has a [repo](https://gitlab.cs.washington.edu/561p-course-staff/mininet-environment) which can be used as an alternative.

I hope that would be helpful.
